dist: trusty
language: tex
sudo: false

install:
  - cp -n texlive* /tmp/
  - source /tmp/texlive_install.sh
  - tlmgr install koma-script etoolbox logreq biblatex-apa csquotes siunitx oberdiek tocloft abstract pdfpages enumitem psnfss ms caption ec l3kernel l3packages zapfding symbol helvetic textpos glossaries xkeyval mfirstuc textcase xfor datatool substr fp tracklang

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - for i in ./*/*.tex; do [ -f "$i" ] || break; file=${i##**/}; directory=${i%"$file"}; cd $directory; pdflatex -interaction=nonstopmode -halt-on-error $file; cd ..; done

before_deploy:
  - source .env

deploy:
  provider: releases
  api_key: $GIT_AUTH
  skip_cleanup: true
  file_glob: true
  file:
    - "./*/*.pdf" 
  on:
    tags: true

deploy:
  provider: releases
  api_key: $GIT_AUTH
  skip_cleanup: true
  file_glob: true
  prerelease: true
  file: "./*/*.pdf"
  tag_name: "v${VERSION}.${TRAVIS_BUILD_NUMBER}"
  name: "v${VERSION}.${TRAVIS_BUILD_NUMBER}"
  on:
    tags: false
    branch: "travis/cd"
